# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gt < Formula
  desc "Git workflow utility with intelligent branch management and automation"
  homepage "https://github.com/pavlovic265/265-gt"
  version "0.56.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pavlovic265/265-gt/releases/download/v0.56.3/265-gt_Darwin_x86_64.tar.gz"
      sha256 "ca9bd1a091d66328328f07b05831f3df5971235aaff986c1bdaf4ca2d407aa48"

      def install
        bin.install "gt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pavlovic265/265-gt/releases/download/v0.56.3/265-gt_Darwin_arm64.tar.gz"
      sha256 "53594f9cd6d5a294465b4449e6906d69eb96b2705ce5e866f90ec257962a01e8"

      def install
        bin.install "gt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pavlovic265/265-gt/releases/download/v0.56.3/265-gt_Linux_x86_64.tar.gz"
      sha256 "bc4be46ae39e8dff9466bff3f6b3344006ccbdb697ba73ec5f7f7ce83b9f8e61"
      def install
        bin.install "gt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pavlovic265/265-gt/releases/download/v0.56.3/265-gt_Linux_arm64.tar.gz"
      sha256 "a3cc9de388e72b60bb438af5a488f1c305712a3025fdf008b1581b7c44b3e4d8"
      def install
        bin.install "gt"
      end
    end
  end

  test do
    system "#{bin}/gt", "--version"
  end
end
