# This file was generated by GoReleaser. DO NOT EDIT.
cask "gt" do
  name "gt"
  desc "Git workflow utility with intelligent branch management and automation"
  homepage "https://github.com/pavlovic265/265-gt"
  version "0.67.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gt"

  on_macos do
    on_intel do
      url "https://github.com/pavlovic265/265-gt/releases/download/v#{version}/265-gt_Darwin_x86_64.tar.gz"
      sha256 "56ec6c78fc3d15684cd769e828672551f50f31bd1f12cc82d348458e5b8628f2"
    end
    on_arm do
      url "https://github.com/pavlovic265/265-gt/releases/download/v#{version}/265-gt_Darwin_arm64.tar.gz"
      sha256 "80ef0e00dd29fdbf2e8c9685c9a7986dfaeafad7e096a47ba188d226e5ddcb29"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pavlovic265/265-gt/releases/download/v#{version}/265-gt_Linux_x86_64.tar.gz"
      sha256 "5d6318272878efc4073306e5a26ba5b980322d5d8a7ca696a0aa7a93b9e64d25"
    end
    on_arm do
      url "https://github.com/pavlovic265/265-gt/releases/download/v#{version}/265-gt_Linux_arm64.tar.gz"
      sha256 "90f9fe892edd706b830dd11b7b357aa4cc7845164f09ba89333d2541f7517c84"
    end
  end

  # No zap stanza required
end
