# This file was generated by GoReleaser. DO NOT EDIT.
cask "gt" do
  name "gt"
  desc "Git workflow utility with intelligent branch management and automation"
  homepage "https://github.com/pavlovic265/265-gt"
  version "0.57.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gt"

  on_macos do
    on_intel do
      url "https://github.com/pavlovic265/265-gt/releases/download/v#{version}/265-gt_Darwin_x86_64.tar.gz"
      sha256 "bb580e000c4d6fc727affcf1d737a37dba06969e99bcbe94bcbc7b0c6befa508"
    end
    on_arm do
      url "https://github.com/pavlovic265/265-gt/releases/download/v#{version}/265-gt_Darwin_arm64.tar.gz"
      sha256 "68abbf53951e0757f6a3de6999b975a36afecd4cf446467b7edf44ed3952582f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pavlovic265/265-gt/releases/download/v#{version}/265-gt_Linux_x86_64.tar.gz"
      sha256 "0241281ebc6c5bba185cbefbb677c374ff273e58fdc01f70d963c4a1ec5f52e7"
    end
    on_arm do
      url "https://github.com/pavlovic265/265-gt/releases/download/v#{version}/265-gt_Linux_arm64.tar.gz"
      sha256 "7d9ba5f86bf78bf5d54e463392ff62d2f824a3d7c8e7888cb1cbdcc9515140c6"
    end
  end

  # No zap stanza required
end
