# This file was generated by GoReleaser. DO NOT EDIT.
cask "gt" do
  name "gt"
  desc "Git workflow utility with intelligent branch management and automation"
  homepage "https://github.com/pavlovic265/265-gt"
  version "0.58.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gt"

  on_macos do
    on_intel do
      url "https://github.com/pavlovic265/265-gt/releases/download/v#{version}/265-gt_Darwin_x86_64.tar.gz"
      sha256 "77eed0cb6cac97fab56f7841bbf732ec7ec8be02c0f63f18146c893553916dfe"
    end
    on_arm do
      url "https://github.com/pavlovic265/265-gt/releases/download/v#{version}/265-gt_Darwin_arm64.tar.gz"
      sha256 "fc2d43a5b111bdadbeedecd677af2bcd8a1c0610a0ebb2e35db360805ba8d1b4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pavlovic265/265-gt/releases/download/v#{version}/265-gt_Linux_x86_64.tar.gz"
      sha256 "64633d84711ccafb078894931ea6f322ae12d09df648ca1537e7a0be7e0b1974"
    end
    on_arm do
      url "https://github.com/pavlovic265/265-gt/releases/download/v#{version}/265-gt_Linux_arm64.tar.gz"
      sha256 "1182947247b98aa0659aee76788685c9a45f4b50807c60ea4451c695b9f87cae"
    end
  end

  # No zap stanza required
end
