# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gt < Formula
  desc "Git workflow utility with intelligent branch management and automation"
  homepage "https://github.com/pavlovic265/265-gt"
  version "0.56.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pavlovic265/265-gt/releases/download/v0.56.4/265-gt_Darwin_x86_64.tar.gz"
      sha256 "fb759b1462422d6f5d2f42c178ad230031b161400df797f67ce6cba85253e55b"

      def install
        bin.install "gt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pavlovic265/265-gt/releases/download/v0.56.4/265-gt_Darwin_arm64.tar.gz"
      sha256 "e4a6d4099b643685cedf867149b74e17d3385d90fe2ccbcc523bf5eea4951e80"

      def install
        bin.install "gt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pavlovic265/265-gt/releases/download/v0.56.4/265-gt_Linux_x86_64.tar.gz"
      sha256 "bffa16014c7f2e3c490523cdc3792800a0690ad61e032dbf79478ebd144621f9"
      def install
        bin.install "gt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pavlovic265/265-gt/releases/download/v0.56.4/265-gt_Linux_arm64.tar.gz"
      sha256 "841c43854ca715ae746d8ca65da489c559ad0834f28813f5a4985109ab60918d"
      def install
        bin.install "gt"
      end
    end
  end

  test do
    system "#{bin}/gt", "--version"
  end
end
